# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - master


permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    # - uses: actions/checkout@v3
    - name: checkout
      shell: bash
      run: |
        meshd --version
        /usr/bin/git config --global --add safe.directory /home/bharathu/actions-runner/_work/PopularMovies/PopularMovies
        /usr/bin/git init /home/bharathu/actions-runner/_work/PopularMovies/PopularMovies
        git remote remove origin
        /usr/bin/git remote add origin https://github.com/Bharath92/PopularMovies.git || true
        git remote -v
        /usr/bin/git config --local gc.auto 0
        meshd git fetch +$GITHUB_SHA:refs/remotes/origin/$GITHUB_REF_NAME --no-tags --prune --progress --no-recurse-submodules --depth=1
        git checkout --progress --force -B $GITHUB_REF_NAME refs/remotes/origin/$GITHUB_REF_NAME
    - name: test
      shell: bash
      run: |
        printenv
        ls -la

        
